// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtxqdzcihxjaiosmffvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0eHFkemNpaHhqYWlvc21mZnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMTMxNjcsImV4cCI6MjA1ODc4OTE2N30.1PCe3yo5Xscz-lKBU6lI9iv7Pu8KcLQwPc8mMCfqK_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);